
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format_sql: true
  security:
    jwt-key: 123456
    token-expired-in: 8640000
