############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
    port: 8088
    tomcat:
        uri-encoding: UTF-8
    max-http-header-size: 80KB
api-package: api