
server:
    port: 8000

api-package: api
spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

wx:
  appid:
  appsecret:
  code2session:
